server:
  port: 5320
netty:
  port: 1100
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
