package com.github.codec.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * string 类型
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * int 类型
   * </pre>
   *
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
